/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as StoreRouteImport } from './routes/store'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TosRouteImport } from './routes/tos'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminContactRouteImport } from './routes/admin.contact'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminLookupRouteImport } from './routes/admin.lookup'
import { Route as AdminManagementRouteImport } from './routes/admin.management'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminReferralsRouteImport } from './routes/admin.referrals'
import { Route as AdminWishlistsRouteImport } from './routes/admin.wishlists'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsApplyRouteImport } from './routes/jobs.apply'
import { Route as StoreIndexRouteImport } from './routes/store.index'
import { Route as StorePackageIdRouteImport } from './routes/store.$packageId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLookupRoute = AdminLookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManagementRoute = AdminManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReferralsRoute = AdminReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWishlistsRoute = AdminWishlistsRouteImport.update({
  id: '/wishlists',
  path: '/wishlists',
  getParentRoute: () => AdminRoute,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRoute,
} as any)
const JobsApplyRoute = JobsApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => JobsRoute,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const StorePackageIdRoute = StorePackageIdRouteImport.update({
  id: '/$packageId',
  path: '/$packageId',
  getParentRoute: () => StoreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/impressum': typeof ImpressumRoute
  '/jobs': typeof JobsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/referral': typeof ReferralRoute
  '/referrals': typeof ReferralsRoute
  '/store': typeof StoreRouteWithChildren
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/tos': typeof TosRoute
  '/wishlist': typeof WishlistRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/lookup': typeof AdminLookupRoute
  '/admin/management': typeof AdminManagementRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/wishlists': typeof AdminWishlistsRoute
  '/jobs/apply': typeof JobsApplyRoute
  '/store/$packageId': typeof StorePackageIdRoute
  '/admin/': typeof AdminIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/store/': typeof StoreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/impressum': typeof ImpressumRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/referral': typeof ReferralRoute
  '/referrals': typeof ReferralsRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/tos': typeof TosRoute
  '/wishlist': typeof WishlistRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/lookup': typeof AdminLookupRoute
  '/admin/management': typeof AdminManagementRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/wishlists': typeof AdminWishlistsRoute
  '/jobs/apply': typeof JobsApplyRoute
  '/store/$packageId': typeof StorePackageIdRoute
  '/admin': typeof AdminIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/store': typeof StoreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/impressum': typeof ImpressumRoute
  '/jobs': typeof JobsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/referral': typeof ReferralRoute
  '/referrals': typeof ReferralsRoute
  '/store': typeof StoreRouteWithChildren
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/tos': typeof TosRoute
  '/wishlist': typeof WishlistRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/lookup': typeof AdminLookupRoute
  '/admin/management': typeof AdminManagementRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/wishlists': typeof AdminWishlistsRoute
  '/jobs/apply': typeof JobsApplyRoute
  '/store/$packageId': typeof StorePackageIdRoute
  '/admin/': typeof AdminIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/store/': typeof StoreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/impressum'
    | '/jobs'
    | '/privacy'
    | '/profile'
    | '/purchases'
    | '/referral'
    | '/referrals'
    | '/store'
    | '/team'
    | '/terms'
    | '/tos'
    | '/wishlist'
    | '/admin/contact'
    | '/admin/logs'
    | '/admin/lookup'
    | '/admin/management'
    | '/admin/partners'
    | '/admin/referrals'
    | '/admin/wishlists'
    | '/jobs/apply'
    | '/store/$packageId'
    | '/admin/'
    | '/jobs/'
    | '/store/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/impressum'
    | '/privacy'
    | '/profile'
    | '/purchases'
    | '/referral'
    | '/referrals'
    | '/team'
    | '/terms'
    | '/tos'
    | '/wishlist'
    | '/admin/contact'
    | '/admin/logs'
    | '/admin/lookup'
    | '/admin/management'
    | '/admin/partners'
    | '/admin/referrals'
    | '/admin/wishlists'
    | '/jobs/apply'
    | '/store/$packageId'
    | '/admin'
    | '/jobs'
    | '/store'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/impressum'
    | '/jobs'
    | '/privacy'
    | '/profile'
    | '/purchases'
    | '/referral'
    | '/referrals'
    | '/store'
    | '/team'
    | '/terms'
    | '/tos'
    | '/wishlist'
    | '/admin/contact'
    | '/admin/logs'
    | '/admin/lookup'
    | '/admin/management'
    | '/admin/partners'
    | '/admin/referrals'
    | '/admin/wishlists'
    | '/jobs/apply'
    | '/store/$packageId'
    | '/admin/'
    | '/jobs/'
    | '/store/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  ImpressumRoute: typeof ImpressumRoute
  JobsRoute: typeof JobsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  PurchasesRoute: typeof PurchasesRoute
  ReferralRoute: typeof ReferralRoute
  ReferralsRoute: typeof ReferralsRoute
  StoreRoute: typeof StoreRouteWithChildren
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  TosRoute: typeof TosRoute
  WishlistRoute: typeof WishlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lookup': {
      id: '/admin/lookup'
      path: '/lookup'
      fullPath: '/admin/lookup'
      preLoaderRoute: typeof AdminLookupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/management': {
      id: '/admin/management'
      path: '/management'
      fullPath: '/admin/management'
      preLoaderRoute: typeof AdminManagementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/referrals': {
      id: '/admin/referrals'
      path: '/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AdminReferralsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wishlists': {
      id: '/admin/wishlists'
      path: '/wishlists'
      fullPath: '/admin/wishlists'
      preLoaderRoute: typeof AdminWishlistsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/apply': {
      id: '/jobs/apply'
      path: '/apply'
      fullPath: '/jobs/apply'
      preLoaderRoute: typeof JobsApplyRouteImport
      parentRoute: typeof JobsRoute
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/$packageId': {
      id: '/store/$packageId'
      path: '/$packageId'
      fullPath: '/store/$packageId'
      preLoaderRoute: typeof StorePackageIdRouteImport
      parentRoute: typeof StoreRoute
    }
  }
}

interface AdminRouteChildren {
  AdminContactRoute: typeof AdminContactRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminLookupRoute: typeof AdminLookupRoute
  AdminManagementRoute: typeof AdminManagementRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminReferralsRoute: typeof AdminReferralsRoute
  AdminWishlistsRoute: typeof AdminWishlistsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContactRoute: AdminContactRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminLookupRoute: AdminLookupRoute,
  AdminManagementRoute: AdminManagementRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminReferralsRoute: AdminReferralsRoute,
  AdminWishlistsRoute: AdminWishlistsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface JobsRouteChildren {
  JobsApplyRoute: typeof JobsApplyRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsApplyRoute: JobsApplyRoute,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface StoreRouteChildren {
  StorePackageIdRoute: typeof StorePackageIdRoute
  StoreIndexRoute: typeof StoreIndexRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StorePackageIdRoute: StorePackageIdRoute,
  StoreIndexRoute: StoreIndexRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  ImpressumRoute: ImpressumRoute,
  JobsRoute: JobsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  PurchasesRoute: PurchasesRoute,
  ReferralRoute: ReferralRoute,
  ReferralsRoute: ReferralsRoute,
  StoreRoute: StoreRouteWithChildren,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  TosRoute: TosRoute,
  WishlistRoute: WishlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
